// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UT_WMSDotnet.Data;

#nullable disable

namespace ut_wms_asp.net.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260610104700_AddHandoverUploadedBy")]
    partial class AddHandoverUploadedBy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UT_WMSDotnet.Models.AdminRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Permissions")
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("admin_roles", (string)null);
                });

            modelBuilder.Entity("UT_WMSDotnet.Models.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("UT_WMSDotnet.Models.Division", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("divisions", (string)null);
                });

            modelBuilder.Entity("UT_WMSDotnet.Models.Location", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("UT_WMSDotnet.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("barcode_type")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("category_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("current_stock")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("image")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("images")
                        .HasColumnType("json");

                    b.Property<int>("initial_stock")
                        .HasColumnType("int");

                    b.Property<int>("is_returnable")
                        .HasColumnType("int");

                    b.Property<int?>("location_id")
                        .HasColumnType("int");

                    b.Property<int>("min_stock")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("position_image")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("transaction_type")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("unit_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("value")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("category_id");

                    b.HasIndex("location_id");

                    b.HasIndex("unit_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("UT_WMSDotnet.Models.ProductVariant", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("color")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("image")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("product_id")
                        .HasColumnType("int");

                    b.Property<string>("size")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("sku")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("product_id");

                    b.ToTable("product_variants", (string)null);
                });

            modelBuilder.Entity("UT_WMSDotnet.Models.ProfileRequest", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("division_id")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("nrp")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("division_id");

                    b.HasIndex("user_id");

                    b.ToTable("profile_requests", (string)null);
                });

            modelBuilder.Entity("UT_WMSDotnet.Models.StockLog", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("product_id")
                        .HasColumnType("int");

                    b.Property<int>("stock_after")
                        .HasColumnType("int");

                    b.Property<int>("stock_before")
                        .HasColumnType("int");

                    b.Property<int>("transaction_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("product_id");

                    b.HasIndex("transaction_id");

                    b.ToTable("stock_logs");
                });

            modelBuilder.Entity("UT_WMSDotnet.Models.Transaction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("admin_notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("applicant_name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("applicant_nrp")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("approver_id")
                        .HasColumnType("int");

                    b.Property<int?>("borrow_duration_days")
                        .HasColumnType("int");

                    b.Property<DateTime?>("borrow_start_date")
                        .HasColumnType("date");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("division_id")
                        .HasColumnType("int");

                    b.Property<string>("documentation_link")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("documentation_notes")
                        .HasColumnType("text");

                    b.Property<string>("documentation_photo")
                        .HasColumnType("text");

                    b.Property<DateTime?>("documentation_uploaded_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("event_date")
                        .HasColumnType("date");

                    b.Property<string>("event_name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("expected_return_date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("handover_approved_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("handover_notes")
                        .HasColumnType("text");

                    b.Property<string>("handover_photo")
                        .HasColumnType("text");

                    b.Property<string>("handover_recipient_name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("handover_timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("handover_uploaded_by")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("is_return_draft")
                        .HasColumnType("int");

                    b.Property<string>("last_revision_stage")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("manager_notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("pending_return_quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("pickup_date")
                        .HasColumnType("date");

                    b.Property<int>("product_id")
                        .HasColumnType("int");

                    b.Property<int?>("product_variant_id")
                        .HasColumnType("int");

                    b.Property<int?>("quantity")
                        .HasColumnType("int");

                    b.Property<string>("rejection_reason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("request_type")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("requester_id")
                        .HasColumnType("int");

                    b.Property<string>("return_condition")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("return_photo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("return_reason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("return_rejection_reason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("return_status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("returned_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("returned_quantity")
                        .HasColumnType("int");

                    b.Property<string>("staff_inventory_notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("used_by")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("id");

                    b.HasIndex("approver_id");

                    b.HasIndex("division_id");

                    b.HasIndex("product_id");

                    b.HasIndex("product_variant_id");

                    b.HasIndex("requester_id");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("UT_WMSDotnet.Models.Unit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("units", (string)null);
                });

            modelBuilder.Entity("UT_WMSDotnet.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("division_id")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("email_verified_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("nrp")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("poin")
                        .HasColumnType("int");

                    b.Property<string>("remember_token")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("division_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("UT_WMSDotnet.Models.UserAdminRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AdminRoleId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminRoleId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("user_admin_roles", (string)null);
                });

            modelBuilder.Entity("UT_WMSDotnet.Models.Product", b =>
                {
                    b.HasOne("UT_WMSDotnet.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UT_WMSDotnet.Models.Location", "Location")
                        .WithMany("Products")
                        .HasForeignKey("location_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UT_WMSDotnet.Models.Unit", "Unit")
                        .WithMany("Products")
                        .HasForeignKey("unit_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("Location");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("UT_WMSDotnet.Models.ProductVariant", b =>
                {
                    b.HasOne("UT_WMSDotnet.Models.Product", "Product")
                        .WithMany("ProductVariants")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("UT_WMSDotnet.Models.ProfileRequest", b =>
                {
                    b.HasOne("UT_WMSDotnet.Models.Division", "Division")
                        .WithMany()
                        .HasForeignKey("division_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UT_WMSDotnet.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Division");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UT_WMSDotnet.Models.StockLog", b =>
                {
                    b.HasOne("UT_WMSDotnet.Models.Product", "Product")
                        .WithMany("StockLogs")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UT_WMSDotnet.Models.Transaction", "Transaction")
                        .WithMany("StockLogs")
                        .HasForeignKey("transaction_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("UT_WMSDotnet.Models.Transaction", b =>
                {
                    b.HasOne("UT_WMSDotnet.Models.User", "Approver")
                        .WithMany()
                        .HasForeignKey("approver_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UT_WMSDotnet.Models.Division", "Division")
                        .WithMany()
                        .HasForeignKey("division_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UT_WMSDotnet.Models.Product", "Product")
                        .WithMany("Transactions")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UT_WMSDotnet.Models.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("product_variant_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UT_WMSDotnet.Models.User", "Requester")
                        .WithMany()
                        .HasForeignKey("requester_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Division");

                    b.Navigation("Product");

                    b.Navigation("ProductVariant");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("UT_WMSDotnet.Models.User", b =>
                {
                    b.HasOne("UT_WMSDotnet.Models.Division", "Division")
                        .WithMany("Users")
                        .HasForeignKey("division_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Division");
                });

            modelBuilder.Entity("UT_WMSDotnet.Models.UserAdminRole", b =>
                {
                    b.HasOne("UT_WMSDotnet.Models.AdminRole", "AdminRole")
                        .WithMany("UserAdminRoles")
                        .HasForeignKey("AdminRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UT_WMSDotnet.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UT_WMSDotnet.Models.User", "User")
                        .WithMany("UserAdminRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdminRole");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UT_WMSDotnet.Models.AdminRole", b =>
                {
                    b.Navigation("UserAdminRoles");
                });

            modelBuilder.Entity("UT_WMSDotnet.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("UT_WMSDotnet.Models.Division", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("UT_WMSDotnet.Models.Location", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("UT_WMSDotnet.Models.Product", b =>
                {
                    b.Navigation("ProductVariants");

                    b.Navigation("StockLogs");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("UT_WMSDotnet.Models.Transaction", b =>
                {
                    b.Navigation("StockLogs");
                });

            modelBuilder.Entity("UT_WMSDotnet.Models.Unit", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("UT_WMSDotnet.Models.User", b =>
                {
                    b.Navigation("UserAdminRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
